const titles=[
{name:"Solo Leveling",type:"Anime",genre:"Action",lang:["Japanese","English","Telugu","Hindi"],year:2024,emoji:"⚔️",bg:"linear-gradient(135deg,#111827,#4c1d95)",desc:"A fantasy action series about a hunter who gains a mysterious system and grows stronger.",official:"https://www.crunchyroll.com/search?q=Solo%20Leveling"},
{name:"Demon Slayer",type:"Anime",genre:"Action",lang:["Japanese","English","Hindi"],year:2019,emoji:"🔥",bg:"linear-gradient(135deg,#7f1d1d,#f59e0b)",desc:"A young swordsman enters a dangerous world of demons while searching for a cure for his sister.",official:"https://www.crunchyroll.com/search?q=Demon%20Slayer"},
{name:"One Piece",type:"Anime",genre:"Adventure",lang:["Japanese","English","Hindi","Tamil"],year:1999,emoji:"☠️",bg:"linear-gradient(135deg,#075985,#fbbf24)",desc:"A pirate crew sails across the Grand Line in search of the legendary One Piece.",official:"https://www.crunchyroll.com/search?q=One%20Piece"},
{name:"Jujutsu Kaisen",type:"Anime",genre:"Action",lang:["Japanese","English","Hindi","Tamil"],year:2020,emoji:"👁️",bg:"linear-gradient(135deg,#172554,#7e22ce)",desc:"Students of a supernatural school fight curses and protect people from dangerous spirits.",official:"https://www.crunchyroll.com/search?q=Jujutsu%20Kaisen"},
{name:"My Hero Academia",type:"Anime",genre:"Superhero",lang:["Japanese","English","Hindi"],year:2016,emoji:"🦸",bg:"linear-gradient(135deg,#14532d,#0ea5e9)",desc:"In a world where superpowers are common, a determined student works toward becoming a hero.",official:"https://www.crunchyroll.com/search?q=My%20Hero%20Academia"},
{name:"Spy x Family",type:"Anime",genre:"Comedy",lang:["Japanese","English","Hindi","Tamil"],year:2022,emoji:"🕵️",bg:"linear-gradient(135deg,#3f0d40,#e11d48)",desc:"A spy, an assassin and a telepath form an unusual family while hiding their secrets.",official:"https://www.crunchyroll.com/search?q=Spy%20x%20Family"},
{name:"Attack on Titan",type:"Anime",genre:"Drama",lang:["Japanese","English","Hindi"],year:2013,emoji:"🏰",bg:"linear-gradient(135deg,#1c1917,#92400e)",desc:"Humanity fights for survival behind enormous walls while uncovering the truth about their world.",official:"https://www.crunchyroll.com/search?q=Attack%20on%20Titan"},
{name:"Naruto",type:"Anime",genre:"Adventure",lang:["Japanese","English","Hindi","Tamil"],year:2002,emoji:"🍥",bg:"linear-gradient(135deg,#9a3412,#facc15)",desc:"A young ninja pursues his dream of becoming the leader of his village.",official:"https://www.crunchyroll.com/search?q=Naruto"},
{name:"Your Name",type:"Movie",genre:"Romance",lang:["Japanese","English","Hindi"],year:2016,emoji:"🌌",bg:"linear-gradient(135deg,#172554,#ec4899)",desc:"Two strangers mysteriously begin experiencing each other's lives across time and distance.",official:"https://www.crunchyroll.com/search?q=Your%20Name"},
{name:"Suzume",type:"Movie",genre:"Fantasy",lang:["Japanese","English","Hindi"],year:2022,emoji:"🚪",bg:"linear-gradient(135deg,#0c4a6e,#a855f7)",desc:"A teenage girl travels across Japan closing mysterious doors connected to a supernatural disaster.",official:"https://www.crunchyroll.com/search?q=Suzume"},
{name:"A Silent Voice",type:"Movie",genre:"Drama",lang:["Japanese","English","Hindi"],year:2016,emoji:"🌸",bg:"linear-gradient(135deg,#1e3a8a,#f472b6)",desc:"A former bully seeks redemption and connection with the classmate he once hurt.",official:"https://www.netflix.com/search?q=A%20Silent%20Voice"},
{name:"Haikyuu!!",type:"Anime",genre:"Sports",lang:["Japanese","English","Hindi"],year:2014,emoji:"🏐",bg:"linear-gradient(135deg,#7c2d12,#f97316)",desc:"A determined volleyball player builds a team and competes at the highest levels.",official:"https://www.crunchyroll.com/search?q=Haikyuu"}
];
const cartoons=["Doraemon","Shin-chan","Ben 10","Tom & Jerry","Pokémon","Avatar"];
let state={q:"",lang:"All",genre:"All"};
const $=s=>document.querySelector(s);
const langs=["All","Japanese","English","Hindi","Telugu","Tamil"];
const genres=["All","Action","Adventure","Comedy","Drama","Fantasy","Romance","Sports","Superhero"];
function chips(items,el,key){el.innerHTML=items.map(x=>`<button class="chip ${state[key]===x?"active":""}" data-key="${key}" data-value="${x}">${x}</button>`).join("");el.querySelectorAll(".chip").forEach(b=>b.onclick=()=>{state[key]=b.dataset.value;render()})}
function card(t){return `<article class="card" data-name="${t.name}"><div class="poster" style="--bg:${t.bg}"><span class="badge">${t.type}</span>${t.emoji}</div><div class="card-body"><h3>${t.name}</h3><div class="muted">${t.year} • ${t.genre} • ${t.lang[0]}</div></div></article>`}
function filtered(){return titles.filter(t=>(state.lang==="All"||t.lang.includes(state.lang))&&(state.genre==="All"||t.genre===state.genre)&&t.name.toLowerCase().includes(state.q.toLowerCase()))}
function attachCards(){document.querySelectorAll(".card").forEach(c=>c.onclick=()=>openModal(titles.find(t=>t.name===c.dataset.name)))}
function render(){chips(langs,$("#languages"),"lang");chips(genres,$("#genres"),"genre");const arr=filtered();$("#grid").innerHTML=arr.map(card).join("");$("#empty").classList.toggle("hidden",arr.length>0);attachCards();$("#movieGrid").innerHTML=titles.filter(t=>t.type==="Movie").map(card).join("");document.querySelectorAll("#movieGrid .card").forEach(c=>c.onclick=()=>openModal(titles.find(t=>t.name===c.dataset.name)));$("#cartoonGrid").innerHTML=cartoons.map(x=>`<div class="mini"><b>${x}</b><span class="muted">Cartoon • Explore title</span></div>`).join("")}
function openModal(t){if(!t)return;$("#modalTitle").textContent=t.name;$("#modalMeta").textContent=`${t.type} • ${t.year} • ${t.genre} • ${t.lang.join(" / ")}`;$("#modalDesc").textContent=t.desc;$("#modalPoster").style.background=t.bg;$("#modalPoster").textContent=t.emoji;$("#watchBtn").href=t.official;$("#modal").classList.remove("hidden");$("#favBtn").textContent=localStorage.getItem("fav:"+t.name)?"♥ In favorites":"♡ Add to favorites";$("#favBtn").onclick=()=>{const k="fav:"+t.name;localStorage.getItem(k)?localStorage.removeItem(k):localStorage.setItem(k,"1");$("#favBtn").textContent=localStorage.getItem(k)?"♥ In favorites":"♡ Add to favorites"}}
$("#search").addEventListener("input",e=>{state.q=e.target.value;render()});$("#searchBtn").onclick=()=>{$("#search").focus();$("#anime").scrollIntoView({behavior:"smooth"})};$("#randomBtn").onclick=()=>openModal(titles[Math.floor(Math.random()*titles.length)]);["#closeModal","#closeX"].forEach(s=>$(s).onclick=()=>$("#modal").classList.add("hidden"));document.addEventListener("keydown",e=>{if(e.key==="Escape")$("#modal").classList.add("hidden")});render();